version: 0.2                                                # Specify aws build system version
run-as: root                                                # Specify what user to run the build as

env:                                                        # Environment specific settings
  shell: /bin/bash                                          # Specify what shell to use when executing
  secrets-manager:
    SLS_CERT_PASSWORD_SECRET_KEY: example_password
  variables:
    FED_PROXY_AUTH_URL: https://benrhine.com/as/authorization.oauth2
    FED_PROXY_AUTH_REDIRECT_URL: https://benrhine.com
    FED_PROXY_TOKEN_URL: https://benrhine.com/as/token.oauth2
    FED_PROXY_TOKEN_REDIRECT_URL: https://benrhine.com
    SLS_CERT_BUCKET: sls-regional-domain-deploy
    SLS_CERT_PATH_NAME: certificates/example.jks
#  git-credential-helper: yes                                # Specify to remember git credentials (this may not be necessary)

cache:
  paths:
    - '/root/.gradle/**/*'
    - '/root/.m2/**/*'
    - '.gradle/**/*'

phases:
  install:
    # Currently both java 17 and  node come installed in the image
    commands:
      - echo "------------------------------------------------- Phase -------------------------------------------------"
      - BUILD_START_TIME=$(($(date +%s%N)/1000000))
      - |
        if [ $CODEBUILD_BUILD_NUMBER ]; then
          echo "Install Phase - CI Build $CODEBUILD_BUILD_NUMBER"
          IS_CI_BUILD=true
        else
          echo "Install Phase - CI Build number is not set, something may be wrong"
        fi
      - echo "--------------------------------------------- Build Details ---------------------------------------------"
      - echo "Current directory -" `pwd`
      - echo "Current Java Version -" `java --version`
      - echo "Current AWS Cli Version -" `aws --version`
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - echo "Current AWS Account - $AWS_ACCOUNT_ID"
      - echo "Current AWS Region - $AWS_REGION"
      - echo "----------------------------------------------- Complete ------------------------------------------------"
  pre_build:
    commands:
    # Nothing to do here
  build:
    commands:
      - ./gradlew integrationTest
  post_build:
    commands:
      - BUILD_END_TIME=$(($(date +%s%N)/1000000))
      - echo "Integration testing complete ... | Runtime - $((BUILD_END_TIME-BUILD_START_TIME)) ms"
reports:
  integration-reports:
    files:
      - "build/test-results/integrationTest/*.xml"
    file-format: "JUNITXML"
  jacoco-report:
    files:
      - 'build/reports/jacoco/integrationTestReports/integrationTestReports.xml'
    file-format: 'JACOCOXML'
